"use client";

import * as React from "react";
import { motion } from "framer-motion";
import {
  ClipboardCheck, Building2, UserCheck, MapPin, Layers, GraduationCap, ShieldCheck,
  Users, BookOpen, Database, HardDrive, FileText, FileSpreadsheet, FileType,
} from "lucide-react";
import { toast } from "sonner";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ExportMenu, type ExportMenuItem } from "./export-menu";
import { PieChart } from "./pie-chart";
import { cn } from "@/lib/utils";
import type { PtcacsStatsData, PtcacsStatusFilter, PtcacsKind } from "@/lib/ptcacs-stats";
import {
  exportStatisticsCsv,
  exportStatisticsXlsx,
  exportStatisticsPdf,
  prettyDate,
  type StatSection,
  type StatsExportMeta,
} from "@/lib/export";

const DATASETS: { key: PtcacsKind; label: string; icon: typeof Building2 }[] = [
  { key: "centers", label: "Assessment Centers", icon: Building2 },
  { key: "assessors", label: "Assessors", icon: UserCheck },
];

const STATUS_TABS: { key: PtcacsStatusFilter; label: string }[] = [
  { key: "all", label: "All" },
  { key: "valid", label: "Valid" },
  { key: "expiring", label: "Expiring" },
  { key: "expired", label: "Expired" },
];

const STATUS_LABEL: Record<PtcacsStatusFilter, string> = {
  all: "All Accreditations",
  valid: "Valid",
  expiring: "Expiring",
  expired: "Expired",
};

const DATASET_LABEL: Record<PtcacsKind, string> = {
  centers: "Assessment Centers",
  assessors: "Competency Assessors",
};

const REPORT_SUBTITLE = "TESDA Region VII · Central Visayas";
const ATTRIBUTION = "This report was generated by the online PTCACs registry of TESDA Region VII.";

const DATASET_SPRING = { type: "spring", stiffness: 380, damping: 32 } as const;

interface Props {
  centers: PtcacsStatsData;
  assessors: PtcacsStatsData;
  source: "supabase" | "local";
}

export function PtcacsStatisticsView({ centers, assessors, source }: Props) {
  const [kind, setKind] = React.useState<PtcacsKind>("centers");
  const [status, setStatus] = React.useState<PtcacsStatusFilter>("all");

  const b = (kind === "centers" ? centers : assessors)[status];
  const entityLabel = kind === "centers" ? "Centers" : "Assessors";
  const entityIcon = kind === "centers" ? Building2 : UserCheck;

  const summary = [
    { label: "Accreditations", value: b.recordCount, icon: ClipboardCheck, color: "text-sky-600 dark:text-sky-400", bg: "bg-sky-100 dark:bg-sky-500/15" },
    { label: entityLabel, value: b.entityCount, icon: entityIcon, color: "text-amber-600 dark:text-amber-400", bg: "bg-amber-100 dark:bg-amber-500/15" },
    { label: "Provinces", value: b.provinceCount, icon: MapPin, color: "text-emerald-600 dark:text-emerald-400", bg: "bg-emerald-100 dark:bg-emerald-500/15" },
    { label: "Sectors", value: b.sectorCount, icon: Layers, color: "text-violet-600 dark:text-violet-400", bg: "bg-violet-100 dark:bg-violet-500/15" },
  ];

  // Build the export payload for the CURRENT dataset + status tab. Uses the full
  // (non-truncated) sector/qualification lists so every count is exported.
  const buildMeta = (): StatsExportMeta => ({
    statusLabel: STATUS_LABEL[status],
    generatedAt: new Date().toLocaleString(),
    reportTitle: `PTCACs — Statistics · ${DATASET_LABEL[kind]}`,
    reportSubtitle: REPORT_SUBTITLE,
    attribution: ATTRIBUTION,
    summary: [
      { label: "Accreditations", value: b.recordCount },
      { label: entityLabel, value: b.entityCount },
      { label: "Provinces", value: b.provinceCount },
      { label: "Sectors", value: b.sectorCount },
    ],
  });
  const buildSections = (): StatSection[] => {
    const sections: StatSection[] = [
      { title: "By Province", slices: b.province },
      { title: "By Validity Status", slices: b.validity },
      { title: "By Sector", slices: b.sectorFull },
    ];
    if (kind === "assessors") {
      if (b.sex) sections.push({ title: "By Sex", slices: b.sex });
      if (b.education) sections.push({ title: "By Educational Attainment", slices: b.education });
    }
    sections.push({ title: "By Qualification", slices: b.qualificationFull });
    return sections;
  };

  const fileBase = `PTCACs ${entityLabel} Statistics (${STATUS_LABEL[status]}) as of - ${prettyDate()}`;
  const exportItems: ExportMenuItem[] = [
    {
      key: "csv",
      label: "CSV (.csv)",
      description: "All breakdowns as one flat table",
      icon: <FileText className="size-4" />,
      onSelect: () => {
        try {
          exportStatisticsCsv(buildMeta(), buildSections(), `${fileBase}.csv`);
          toast.success("Statistics exported to CSV");
        } catch (e) {
          console.error(e);
          toast.error("CSV export failed. Please try again.");
        }
      },
    },
    {
      key: "xlsx",
      label: "Excel workbook (.xlsx)",
      description: "A formatted sheet per breakdown",
      icon: <FileSpreadsheet className="size-4" />,
      onSelect: async () => {
        try {
          await exportStatisticsXlsx(buildMeta(), buildSections(), `${fileBase}.xlsx`);
          toast.success("Statistics exported to Excel");
        } catch (e) {
          console.error(e);
          toast.error("Excel export failed. Please try again.");
        }
      },
    },
    {
      key: "pdf",
      label: "PDF report (.pdf)",
      description: "Clean report with logo & per-count tables",
      icon: <FileType className="size-4" />,
      onSelect: async () => {
        try {
          await exportStatisticsPdf(buildMeta(), buildSections(), `${fileBase}.pdf`);
          toast.success("Statistics report exported to PDF");
        } catch (e) {
          console.error(e);
          toast.error("PDF export failed. Please try again.");
        }
      },
    },
  ];

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <h1 className="text-xl font-bold tracking-tight sm:text-2xl">Statistics</h1>
          <p className="text-sm text-muted-foreground">
            Distribution of accredited competency assessment {kind === "centers" ? "centers" : "assessors"} across Region VII — Central Visayas.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Badge
            variant="outline"
            className={cn(
              "gap-1 text-[11px]",
              source === "supabase"
                ? "border-emerald-500/30 text-emerald-600 dark:text-emerald-400"
                : "text-muted-foreground",
            )}
          >
            {source === "supabase" ? (
              <><Database className="size-3" /> Live · Supabase</>
            ) : (
              <><HardDrive className="size-3" /> Local snapshot</>
            )}
          </Badge>
          <ExportMenu items={exportItems} label="Export" disabled={b.recordCount === 0} />
        </div>
      </div>

      {/* Dataset toggle (Centers / Assessors) */}
      <div className="flex w-fit rounded-lg bg-muted p-1">
        {DATASETS.map((d) => {
          const active = kind === d.key;
          return (
            <button
              key={d.key}
              type="button"
              onClick={() => setKind(d.key)}
              aria-pressed={active}
              className={cn(
                "relative flex items-center gap-1.5 rounded-md px-3 py-1.5 text-sm font-medium transition-colors",
                "focus-visible:ring-2 focus-visible:ring-ring/50 focus-visible:outline-none",
                active ? "text-foreground" : "text-muted-foreground hover:text-foreground",
              )}
            >
              {active && (
                <motion.span
                  layoutId="ptcacs-stats-dataset"
                  transition={DATASET_SPRING}
                  className="absolute inset-0 rounded-md bg-card shadow-sm"
                />
              )}
              <d.icon className="relative z-10 size-4" />
              <span className="relative z-10">{d.label}</span>
            </button>
          );
        })}
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        {summary.map((s, i) => (
          <motion.div
            key={`${kind}-${s.label}`}
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.06 }}
            whileHover={{ y: -4 }}
          >
            <Card className="flex-row items-center gap-4 p-5">
              <div className={`flex size-12 items-center justify-center rounded-xl ${s.bg} ${s.color}`}>
                <s.icon className="size-6" />
              </div>
              <div>
                <p className="text-2xl font-bold tnum">{s.value.toLocaleString()}</p>
                <p className="text-sm text-muted-foreground">{s.label}</p>
              </div>
            </Card>
          </motion.div>
        ))}
      </div>

      {/* Status filter */}
      <div className="flex flex-wrap gap-2">
        {STATUS_TABS.map((t) => (
          <Button
            key={t.key}
            size="sm"
            variant={status === t.key ? "default" : "outline"}
            onClick={() => setStatus(t.key)}
            className={cn(status === t.key && "pointer-events-none")}
          >
            {t.label}
          </Button>
        ))}
      </div>

      {/* Charts */}
      {b.recordCount === 0 ? (
        <Card className="min-h-[30vh] items-center justify-center gap-2 p-8 text-muted-foreground">
          <Layers className="size-10" />
          <p>No accreditations to chart for this filter.</p>
        </Card>
      ) : (
        <motion.div
          key={`${kind}-${status}`}
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.25, ease: "easeOut" }}
          className="grid grid-cols-1 gap-4 xl:grid-cols-2"
        >
          <PieChart title="By Province" data={b.province} unit="accreditations" icon={<MapPin className="size-4 text-amber-600 dark:text-amber-400" />} />
          <PieChart title="By Validity Status" data={b.validity} unit="accreditations" icon={<ShieldCheck className="size-4 text-emerald-600 dark:text-emerald-400" />} />
          <PieChart title="By Sector" data={b.sector} totalCategories={b.sectorCount} unit="accreditations" icon={<Layers className="size-4 text-violet-600 dark:text-violet-400" />} />
          {kind === "assessors" && b.sex && (
            <PieChart title="By Sex" data={b.sex} unit="accreditations" icon={<Users className="size-4 text-rose-600 dark:text-rose-400" />} />
          )}
          {kind === "assessors" && b.education && (
            <PieChart title="By Educational Attainment" data={b.education} unit="accreditations" icon={<BookOpen className="size-4 text-cyan-600 dark:text-cyan-400" />} />
          )}
          <PieChart
            title="By Qualification"
            data={b.qualification}
            totalCategories={b.qualCount}
            unit="accreditations"
            icon={<GraduationCap className="size-4 text-emerald-600 dark:text-emerald-400" />}
          />
        </motion.div>
      )}
    </div>
  );
}
